[package]
name = "choose-your-xml"
version = "0.1.0"
authors = ["Reizner Evgeniy <razrfalcon@gmail.com>"]

[dev-dependencies]
dummy_xml = "0.1.6"
bencher = "0.1"
xml-rs = "0.7"
quick-xml = "0.10"
xml5ever = "0.11"
sxd-document = "0.2"

[[bench]]
name = "xml"
harness = false
